 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/contactmessages", type: :request do
  # Contactmessage. As you add validations to Contactmessage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Contactmessage.create! valid_attributes
      get contactmessages_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      contactmessage = Contactmessage.create! valid_attributes
      get contactmessage_url(contactmessage)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_contactmessage_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      contactmessage = Contactmessage.create! valid_attributes
      get edit_contactmessage_url(contactmessage)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Contactmessage" do
        expect {
          post contactmessages_url, params: { contactmessage: valid_attributes }
        }.to change(Contactmessage, :count).by(1)
      end

      it "redirects to the created contactmessage" do
        post contactmessages_url, params: { contactmessage: valid_attributes }
        expect(response).to redirect_to(contactmessage_url(Contactmessage.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Contactmessage" do
        expect {
          post contactmessages_url, params: { contactmessage: invalid_attributes }
        }.to change(Contactmessage, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post contactmessages_url, params: { contactmessage: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested contactmessage" do
        contactmessage = Contactmessage.create! valid_attributes
        patch contactmessage_url(contactmessage), params: { contactmessage: new_attributes }
        contactmessage.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the contactmessage" do
        contactmessage = Contactmessage.create! valid_attributes
        patch contactmessage_url(contactmessage), params: { contactmessage: new_attributes }
        contactmessage.reload
        expect(response).to redirect_to(contactmessage_url(contactmessage))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        contactmessage = Contactmessage.create! valid_attributes
        patch contactmessage_url(contactmessage), params: { contactmessage: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested contactmessage" do
      contactmessage = Contactmessage.create! valid_attributes
      expect {
        delete contactmessage_url(contactmessage)
      }.to change(Contactmessage, :count).by(-1)
    end

    it "redirects to the contactmessages list" do
      contactmessage = Contactmessage.create! valid_attributes
      delete contactmessage_url(contactmessage)
      expect(response).to redirect_to(contactmessages_url)
    end
  end
end
