 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/ilces", type: :request do
  # Ilce. As you add validations to Ilce, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Ilce.create! valid_attributes
      get ilces_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      ilce = Ilce.create! valid_attributes
      get ilce_url(ilce)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_ilce_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      ilce = Ilce.create! valid_attributes
      get edit_ilce_url(ilce)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Ilce" do
        expect {
          post ilces_url, params: { ilce: valid_attributes }
        }.to change(Ilce, :count).by(1)
      end

      it "redirects to the created ilce" do
        post ilces_url, params: { ilce: valid_attributes }
        expect(response).to redirect_to(ilce_url(Ilce.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Ilce" do
        expect {
          post ilces_url, params: { ilce: invalid_attributes }
        }.to change(Ilce, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post ilces_url, params: { ilce: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested ilce" do
        ilce = Ilce.create! valid_attributes
        patch ilce_url(ilce), params: { ilce: new_attributes }
        ilce.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the ilce" do
        ilce = Ilce.create! valid_attributes
        patch ilce_url(ilce), params: { ilce: new_attributes }
        ilce.reload
        expect(response).to redirect_to(ilce_url(ilce))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        ilce = Ilce.create! valid_attributes
        patch ilce_url(ilce), params: { ilce: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested ilce" do
      ilce = Ilce.create! valid_attributes
      expect {
        delete ilce_url(ilce)
      }.to change(Ilce, :count).by(-1)
    end

    it "redirects to the ilces list" do
      ilce = Ilce.create! valid_attributes
      delete ilce_url(ilce)
      expect(response).to redirect_to(ilces_url)
    end
  end
end
