 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/mahales", type: :request do
  # Mahale. As you add validations to Mahale, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Mahale.create! valid_attributes
      get mahales_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      mahale = Mahale.create! valid_attributes
      get mahale_url(mahale)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_mahale_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      mahale = Mahale.create! valid_attributes
      get edit_mahale_url(mahale)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Mahale" do
        expect {
          post mahales_url, params: { mahale: valid_attributes }
        }.to change(Mahale, :count).by(1)
      end

      it "redirects to the created mahale" do
        post mahales_url, params: { mahale: valid_attributes }
        expect(response).to redirect_to(mahale_url(Mahale.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Mahale" do
        expect {
          post mahales_url, params: { mahale: invalid_attributes }
        }.to change(Mahale, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post mahales_url, params: { mahale: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested mahale" do
        mahale = Mahale.create! valid_attributes
        patch mahale_url(mahale), params: { mahale: new_attributes }
        mahale.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the mahale" do
        mahale = Mahale.create! valid_attributes
        patch mahale_url(mahale), params: { mahale: new_attributes }
        mahale.reload
        expect(response).to redirect_to(mahale_url(mahale))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        mahale = Mahale.create! valid_attributes
        patch mahale_url(mahale), params: { mahale: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested mahale" do
      mahale = Mahale.create! valid_attributes
      expect {
        delete mahale_url(mahale)
      }.to change(Mahale, :count).by(-1)
    end

    it "redirects to the mahales list" do
      mahale = Mahale.create! valid_attributes
      delete mahale_url(mahale)
      expect(response).to redirect_to(mahales_url)
    end
  end
end
